# Generated by Django 3.1.7 on 2021-04-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210402_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blogger_Phone_Number', models.CharField(max_length=20)),
                ('Blogger_Name', models.CharField(max_length=20)),
                ('Blogger_email', models.EmailField(max_length=254)),
                ('Blog_Detail', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
